# Generated by Django 4.2.2 on 2023-06-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_location', models.CharField(blank=True, max_length=100)),
                ('farm_size', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('contact_address', models.TextField(blank=True, max_length=100)),
                ('extention', models.CharField(blank=True, max_length=100)),
                ('farm', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('contact_address', models.TextField(blank=True, max_length=100)),
                ('extention', models.CharField(blank=True, max_length=100)),
                ('farm', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
