# Generated by Django 4.2.2 on 2023-06-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('date_visit', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='farmers',
            name='date_visit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='officer',
            name='date_visit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
